name: React Native to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4
      
      # Login to Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      
      # Change to project directory
      - name: Change to project directory
        run: |
          cd react-native-tests
      
      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npx react-native-configure
      
      # Build React Native Web
      - name: Build React Native Web
        run: |
          npm run build
          npx expo build:web
      
      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ./web-build
