name: React Native Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - uses: actions/checkout@v3
      
      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      # Install dependencies
      - name: Install Dependencies
        run: |
          npm ci
      
      # Cache Jest configuration
      - name: Cache Jest Config
        uses: actions/cache@v3
        id: jest-config-cache
        paths:
          - node_modules/.cache/jest
      
      # Run tests
      - name: Run Tests
        run: |
          npm test
