name: Deploy to Expo with EAS

on:
  push:
    branches:
      - main  # Remplacez par la branche que vous souhaitez surveiller

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'  # Utilisez une version de Node.js qui supporte les nouvelles fonctionnalités JavaScript

      - name: Install dependencies
        run: npm install
        working-directory: react-native-tests

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Login to Expo
        run: |
          echo "Logging in to Expo..."
          npx expo-cli login -u mafyou -p ${{ secrets.EXPO_TOKEN }} --non-interactive
        working-directory: react-native-tests

      - name: Publish update with EAS
        run: eas update --auto
        working-directory: react-native-tests
