name: Deploy to Expo

on:
  push:
    branches:
      - main  # Remplacez par la branche que vous souhaitez surveiller

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Utilisez la version de Node.js que vous préférez

      - name: Install dependencies
        run: npm install

      - name: Publish to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx expo publish
